# Generated by Django 5.0.7 on 2024-07-15 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('desc', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('time', models.IntegerField()),
                ('instructions', models.TextField()),
                ('img', models.CharField(max_length=50)),
            ],
        ),
    ]
