# Generated by Django 5.0.7 on 2024-07-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='img',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
