# Generated by Django 5.0.7 on 2024-07-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_plate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
